server.port=8090
logging.level.root=INFO
# Set specific levels for Spring Framework or your own packages
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.authorization=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG


# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Logging (as we discussed)
logging.level.org.springframework.security=DEBUG